{
  "name": "Noorisys_Final_Project",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "StudentsPerformance",
        "lineageTag": "4c69ad51-a960-45b7-8f90-518537794e15",
        "columns": [
          {
            "name": "Student ID",
            "dataType": "string",
            "sourceColumn": "Student ID",
            "lineageTag": "e908fdaf-0202-4abe-ba0a-50dfa67d1e9a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "lineageTag": "2285418f-4938-4ee2-aba8-2b65f2d287ae",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Race/Ethnicity",
            "dataType": "string",
            "sourceColumn": "Race/Ethnicity",
            "lineageTag": "8ca5e498-b71a-4ddc-a048-77c203755b8f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Parent Education",
            "dataType": "string",
            "sourceColumn": "Parent Education",
            "lineageTag": "0fa4ee0d-3f3a-4553-82ce-9e951a2b688d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Lunch",
            "dataType": "string",
            "sourceColumn": "Lunch",
            "lineageTag": "f8f8a9b8-65ac-45c5-a982-602d7ecd7dda",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Test Preparation Course",
            "dataType": "string",
            "sourceColumn": "Test Preparation Course",
            "lineageTag": "34ace2c5-e200-492e-b5d6-72caf20a1326",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Math Score",
            "dataType": "int64",
            "sourceColumn": "Math Score",
            "formatString": "0",
            "lineageTag": "96564674-16e1-49b8-b1d6-98929e1cf224",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reading Score",
            "dataType": "int64",
            "sourceColumn": "Reading Score",
            "formatString": "0",
            "lineageTag": "8894263a-12a6-4603-9bc3-127dfa3db5df",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Writing Score",
            "dataType": "int64",
            "sourceColumn": "Writing Score",
            "formatString": "0",
            "lineageTag": "73666e53-f589-4728-b50c-7ca6627cc75c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Score",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "([Math Score]+[Reading Score]+[Writing Score]) / 3"
            ],
            "formatString": "0",
            "lineageTag": "3f1dfc69-97ca-46d0-b7fb-a819866829c0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Grade",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Score]>=95,\"O\",",
              "    [Score]>=81,\"A\",",
              "    [Score]>=71,\"B\",",
              "    [Score]>=61,\"C\",",
              "    [Score]>=51,\"D\",",
              "    [Score]>=41,\"E\",",
              "    \"F\"",
              ")"
            ],
            "lineageTag": "696e40aa-9ff2-47aa-b216-20394b5ae5c5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "StudentsPerformance",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"F:\\StudentsPerformance.xlsx\"), null, true),",
                "    StudentsPerformance_Sheet = Source{[Item=\"StudentsPerformance\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(StudentsPerformance_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Student id\", type text}, {\"gender\", type text}, {\"race/ethnicity\", type text}, {\"parent education\", type text}, {\"lunch\", type text}, {\"test preparation course\", type text}, {\"math score\", Int64.Type}, {\"reading score\", Int64.Type}, {\"writing score\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"gender\", \"Gender\"}, {\"race/ethnicity\", \"Race/Ethnicity\"}, {\"parent education\", \"Parent Education\"}, {\"lunch\", \"Lunch\"}, {\"test preparation course\", \"Test Preparation Course\"}, {\"math score\", \"Math Score\"}, {\"reading score\", \"Reading Score\"}, {\"writing score\", \"Writing Score\"}, {\"Student id\", \"Student ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "_Measure",
        "lineageTag": "9a8b0289-321d-4cdd-846b-e9a8e1bbd74f",
        "partitions": [
          {
            "name": "_Measure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "No of Students",
            "expression": "DISTINCTCOUNT(StudentsPerformance[Student ID])",
            "formatString": "#,0",
            "displayFolder": "Base Measures",
            "lineageTag": "24884d27-616d-4e30-9172-179824f2b4c4"
          },
          {
            "name": "Average Score",
            "expression": "AVERAGE(StudentsPerformance[Score])",
            "formatString": "0.0",
            "lineageTag": "76641d57-07c1-41dd-85eb-011e63545561"
          },
          {
            "name": "Avg Math",
            "expression": "AVERAGE(StudentsPerformance[Math Score])",
            "lineageTag": "8f0f9d23-7b87-44a0-814d-6ebefeefcd9e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Reading",
            "expression": "AVERAGE(StudentsPerformance[Reading Score])",
            "lineageTag": "2e30e99a-0857-44ae-954c-25f829e062c7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Writing",
            "expression": "AVERAGE(StudentsPerformance[Writing Score])",
            "lineageTag": "d916dd50-781f-4b98-9824-f5f5ce8ee7dc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Male Students",
            "expression": [
              "",
              "VAR MaleCount =",
              "    CALCULATE([No of Students], StudentsPerformance[Gender] = \"male\")",
              "VAR TotalCount =",
              "    [No of Students]",
              "VAR MalePercent =",
              "    DIVIDE(MaleCount, TotalCount, 0)",
              "RETURN",
              "    FORMAT(MalePercent, \"0.0%\")",
              ""
            ],
            "lineageTag": "ebc82d6a-3b4c-4340-a595-c8a1c32ce562"
          },
          {
            "name": "Female Students",
            "expression": [
              "",
              "VAR FemaleCount =",
              "    CALCULATE([No of Students], StudentsPerformance[Gender] = \"female\")",
              "VAR TotalCount =",
              "    [No of Students]",
              "VAR FemalePercent =",
              "    DIVIDE(FemaleCount, TotalCount, 0)",
              "RETURN",
              "    FORMAT(FemalePercent, \"0.0%\")",
              ""
            ],
            "lineageTag": "f41cc0d7-e368-49d2-843e-f03eb0ea72e0"
          },
          {
            "name": "Min Score",
            "expression": "MIN(StudentsPerformance[Score])",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "656cebd8-72c7-4223-b92e-413f96ad75e2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Max Score",
            "expression": "MAX(StudentsPerformance[Score])",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "87a65f1a-581e-4e41-8685-7d85b158d10e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Median Score",
            "expression": "MEDIAN(StudentsPerformance[Score])",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "731f2d40-00d6-477c-a571-9ce8cea2301a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Score Pctile 25",
            "expression": [
              "",
              "PERCENTILE.INC('StudentsPerformance'[Score],0.25)"
            ],
            "displayFolder": "Boxplot Measures",
            "lineageTag": "539ef731-27fe-42b5-b048-dba1ac24acac",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Score Pctile 75",
            "expression": [
              "",
              "PERCENTILE.INC('StudentsPerformance'[Score],0.75)"
            ],
            "displayFolder": "Boxplot Measures",
            "lineageTag": "6c061df0-ddf1-4fd4-bc9f-e8cf1d25d63c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Score IQR",
            "expression": "[Score Pctile 75]-[Score Pctile 25]",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "1a7a559d-eec2-4b86-824c-55886cd54a09",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Score IQR 25-50",
            "expression": "[Median Score]-[Score Pctile 25]",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "0dfbf142-a3d1-48e9-b4c8-49773914cea1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Score IQR 50-75",
            "expression": "[Score Pctile 75]-[Median Score]",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "22c5e7a3-ab06-4353-93e8-721b1d49ca0c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Y axis Max",
            "expression": "[Max Score]*1.1",
            "displayFolder": "Boxplot Measures",
            "lineageTag": "81052ec5-c2a8-43a1-9eb0-1eb21bd6bf25",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Math Donut Chart",
            "expression": [
              "",
              "VAR Subject = \"Math\"",
              "VAR AvgScore = [Avg Math]",
              "VAR MaxScore = 100",
              "VAR ProgressValue = AvgScore / MaxScore * 100",
              "VAR DisplayValue = MIN(ProgressValue, 100)",
              "VAR Radius = 52",
              "VAR CircumferenceValue = 2 * PI() * Radius",
              "VAR ProgressLength = (DisplayValue / 100) * CircumferenceValue",
              "VAR CenterX = 60",
              "VAR CenterY = 60",
              "VAR BackgroundStrokeWidth = 12",
              "VAR ProgressStrokeWidth = 16",
              "VAR Color = \"#071C13\"",
              "",
              "RETURN",
              "\"data:image/svg+xml;utf8,",
              "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='260' height='260'>",
              "  <circle cx='\" & CenterX & \"' cy='\" & CenterY & \"' r='\" & Radius & \"' fill='none' stroke='#E5F2F1' stroke-width='\" & BackgroundStrokeWidth & \"' />",
              "  <circle cx='\" & CenterX & \"' cy='\" & CenterY & \"' r='\" & Radius & \"' fill='none' stroke='\" & Color & \"' stroke-width='\" & ProgressStrokeWidth & \"' stroke-dasharray='\" & CircumferenceValue & \"' stroke-dashoffset='\" & (CircumferenceValue - ProgressLength) & \"' />",
              "  <text x='50%' y='50%' text-anchor='middle' alignment-baseline='middle' font-size='16' font-family='Arial' fill='#000000'>\" & FORMAT(ProgressValue, \"0.0\") & \"%</text>",
              "  <text x='50%' y='62%' text-anchor='middle' alignment-baseline='middle' font-size='14' font-family='Arial' fill='#000000'>\" & Subject & \"</text>",
              "</svg>\"",
              ""
            ],
            "displayFolder": "SVG Measures",
            "lineageTag": "0ba13183-7671-4e42-a2e3-6ca099a20b50",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Reading Donut Chart",
            "expression": [
              "",
              "VAR Subject = \"Reading\"",
              "VAR AvgScore = [Avg Reading]",
              "VAR MaxScore = 100",
              "VAR ProgressValue = AvgScore / MaxScore * 100",
              "VAR DisplayValue = MIN(ProgressValue, 100)",
              "VAR Radius = 52",
              "VAR CircumferenceValue = 2 * PI() * Radius",
              "VAR ProgressLength = (DisplayValue / 100) * CircumferenceValue",
              "VAR CenterX = 60",
              "VAR CenterY = 60",
              "VAR BackgroundStrokeWidth = 12",
              "VAR ProgressStrokeWidth = 16",
              "VAR Color = \"#071C13\"",
              "",
              "RETURN",
              "\"data:image/svg+xml;utf8,",
              "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='260' height='260'>",
              "  <circle cx='\" & CenterX & \"' cy='\" & CenterY & \"' r='\" & Radius & \"' fill='none' stroke='#E5F2F1' stroke-width='\" & BackgroundStrokeWidth & \"' />",
              "  <circle cx='\" & CenterX & \"' cy='\" & CenterY & \"' r='\" & Radius & \"' fill='none' stroke='\" & Color & \"' stroke-width='\" & ProgressStrokeWidth & \"' stroke-dasharray='\" & CircumferenceValue & \"' stroke-dashoffset='\" & (CircumferenceValue - ProgressLength) & \"' />",
              "  <text x='50%' y='50%' text-anchor='middle' alignment-baseline='middle' font-size='16' font-family='Arial' fill='#000000'>\" & FORMAT(ProgressValue, \"0.0\") & \"%</text>",
              "  <text x='50%' y='62%' text-anchor='middle' alignment-baseline='middle' font-size='14' font-family='Arial' fill='#000000'>\" & Subject & \"</text>",
              "</svg>\"",
              ""
            ],
            "displayFolder": "SVG Measures",
            "lineageTag": "8fe15828-3275-43d1-a159-a34c4c788096",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Writing Donut Chart",
            "expression": [
              "",
              "VAR Subject = \"Writing\"",
              "VAR AvgScore = [Avg Writing]",
              "VAR MaxScore = 100",
              "VAR ProgressValue = AvgScore / MaxScore * 100",
              "VAR DisplayValue = MIN(ProgressValue, 100)",
              "VAR Radius = 52",
              "VAR CircumferenceValue = 2 * PI() * Radius",
              "VAR ProgressLength = (DisplayValue / 100) * CircumferenceValue",
              "VAR CenterX = 60",
              "VAR CenterY = 60",
              "VAR BackgroundStrokeWidth = 12",
              "VAR ProgressStrokeWidth = 16",
              "VAR Color = \"#071C13\"",
              "",
              "RETURN",
              "\"data:image/svg+xml;utf8,",
              "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='260' height='260'>",
              "  <circle cx='\" & CenterX & \"' cy='\" & CenterY & \"' r='\" & Radius & \"' fill='none' stroke='#E5F2F1' stroke-width='\" & BackgroundStrokeWidth & \"' />",
              "  <circle cx='\" & CenterX & \"' cy='\" & CenterY & \"' r='\" & Radius & \"' fill='none' stroke='\" & Color & \"' stroke-width='\" & ProgressStrokeWidth & \"' stroke-dasharray='\" & CircumferenceValue & \"' stroke-dashoffset='\" & (CircumferenceValue - ProgressLength) & \"' />",
              "  <text x='50%' y='50%' text-anchor='middle' alignment-baseline='middle' font-size='16' font-family='Arial' fill='#000000'>\" & FORMAT(ProgressValue, \"0.0\") & \"%</text>",
              "  <text x='50%' y='62%' text-anchor='middle' alignment-baseline='middle' font-size='14' font-family='Arial' fill='#000000'>\" & Subject & \"</text>",
              "</svg>\"",
              ""
            ],
            "displayFolder": "Boxplot Measures",
            "lineageTag": "9107219f-2946-41e7-b5f7-2cc3d8b2354d",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Student Score Bar Chart",
            "expression": [
              "",
              "VAR AvgScore = [Average Score] // Replace with your actual measure",
              "VAR MaxScore = 100",
              "VAR ProgressValue = AvgScore / MaxScore * 100",
              "VAR BarHeight = 20",
              "VAR BarY = 20",
              "VAR BarWidth = 300",
              "VAR ProgressPercent = DIVIDE(ProgressValue, 100, 0)",
              "",
              "// --- COLOR DEFINITIONS ---",
              "VAR RedColor = \"#FF4C4C\"",
              "VAR AmberColor = \"#FFA500\"",
              "VAR GreenColor = \"#13A806\"",
              "",
              "VAR FinalColor =",
              "    SWITCH(",
              "        TRUE(),",
              "        ProgressValue >= 75, GreenColor,",
              "        ProgressValue >= 50, AmberColor,",
              "        ProgressValue < 50, RedColor,",
              "        GreenColor",
              "    )",
              "",
              "RETURN",
              "\"data:image/svg+xml;utf8,",
              "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 \" & BarWidth & \" 60' preserveAspectRatio='none' width='\" & BarWidth & \"' height='60'>",
              "  <rect x='0' y='\" & BarY & \"' width='\" & BarWidth & \"' height='\" & BarHeight & \"' fill='#E0E0E0' rx='5' ry='5'/>",
              "  <rect x='0' y='\" & BarY & \"' width='\" & (ProgressPercent * BarWidth) & \"' height='\" & BarHeight & \"' fill='\" & FinalColor & \"' rx='5' ry='5'/>",
              "</svg>\"",
              ""
            ],
            "displayFolder": "SVG Measures",
            "lineageTag": "3baed538-9694-4534-964b-9ca628070f01",
            "dataCategory": "ImageUrl"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Grade Sort",
        "lineageTag": "7aeb1f3a-176e-4b08-b76b-740bb86d3870",
        "columns": [
          {
            "name": "Grade",
            "dataType": "string",
            "sourceColumn": "Grade",
            "sortByColumn": "Grade Order",
            "lineageTag": "64767513-7b57-45e0-9411-6078b1b6635b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Grade Order",
            "dataType": "int64",
            "sourceColumn": "Grade Order",
            "formatString": "0",
            "lineageTag": "6deb6bc5-e9a8-4fa8-9799-145327451ab6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Grade Sort",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"HcapEQAgEAPAXqIx/JrXUsDN9d8GmaxaMzwERHgwDC5pk8va4oq2uaodrmmX63D/\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Grade = _t, #\"Grade Order\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Grade\", type text}, {\"Grade Order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Metric",
        "lineageTag": "50f8f615-1380-4f18-9f05-452687d9e61f",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Metric",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Metric Order",
            "lineageTag": "faf16480-8246-4fd8-8407-9cff12c7fee6",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Metric Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Metric Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Metric Order",
            "lineageTag": "802f5629-62f9-44e7-a4d4-f1b18d1c9857",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Metric Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "383b76f9-07b3-446d-b568-c06365fdcbd1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Metric",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Gender\", NAMEOF('StudentsPerformance'[Gender]), 0),",
                "    (\"Parent Education\", NAMEOF('StudentsPerformance'[Parent Education]), 1),",
                "    (\"Race/Ethnicity\", NAMEOF('StudentsPerformance'[Race/Ethnicity]), 2),",
                "    (\"Test Preparation Course\", NAMEOF('StudentsPerformance'[Test Preparation Course]), 3),",
                "    (\"Lunch\", NAMEOF('StudentsPerformance'[Lunch]), 4)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "455be9255bd2454e98a4353f1fc1c861"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6b03d8a5-17eb-db31-af7a-0c77dbfece06",
        "fromTable": "StudentsPerformance",
        "fromColumn": "Grade",
        "toTable": "Grade Sort",
        "toColumn": "Grade"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"StudentsPerformance\",\"_Measure\",\"Grade Sort\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.144.1378.0 (25.06)+cba1e61f16ea36d44901f06fa446299040122394"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  }
}